services:
  web:
    image: webimg:1.00
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  announcement-api:
    image: announcement-api:1.00
    environment:
      MYSQL_PASSWORD: hThKPEq93f
      MYSQL_USERNAME: root
      MYSQL_DATABASE: sas
      DB_HOST: sas-database-1 
      DB_PORT: 3306
    depends_on:
      - database
#      condition: service_completed_successfully
    build:
      context: ./announcement-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - sas_network

  database:
    image: mysql:8.0.32
    # container_name: DB_HOST
    environment:
      MYSQL_ROOT_PASSWORD: hThKPEq93f
      MYSQL_DATABASE: sas
      LANG: en_US.UTF-8
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql/
      - ./database/src/init-scripts/:/docker-entrypoint-initdb.d/
      - ./database/src/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    networks:
      - sas_network
volumes:
  dbdata:
networks:
  sas_network:
